### ISSUE TITLE
Ocular Exception when tests run on Grid

### ISSUE THREAD

**Issue by anoop5i** [vinsguru/ocular#7] opened 2018-12-17 14:35 UTC
The tests are working fine if I run locally. Is there any workaround to get these working on Selenium Grid?

```
com.testautomationguru.ocular.exception.OcularException: Unable to get page snapshot
	at com.testautomationguru.ocular.comparator.ImageUtil.getPageSnapshot(ImageUtil.java:33)
	at com.testautomationguru.ocular.comparator.ImageUtil.getElementSnapshot(ImageUtil.java:42)
	at com.testautomationguru.ocular.sample.SampleBuilderImpl.element(SampleBuilderImpl.java:46)
	at com.insight.automation.steps.reports.speedByClass.SpeedLineChartSnap.compare(SpeedLineChartSnap.java:31)
	at com.insight.automation.steps.reports.speedByClass.SpeedByClassLineChartSteps.iCanSeeTheLineChartInTheSpeedByClassReportIsMatchingTheSnapshot(SpeedByClassLineChartSteps.java:32)
	at ✽.I can see the line chart in the speed by class report is matching the snapshot(C:/Users/Tester/.jenkins/workspace/FT - Grid/src/test/resources/features/modernUI/reports/speedByClass/LineChartSpeedByClass_4710.feature:14)
Caused by: java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1305)
	at com.testautomationguru.ocular.comparator.ImageUtil.getPageSnapshot(ImageUtil.java:31)
	at com.testautomationguru.ocular.comparator.ImageUtil.getElementSnapshot(ImageUtil.java:42)
	at com.testautomationguru.ocular.sample.SampleBuilderImpl.element(SampleBuilderImpl.java:46)
	at com.insight.automation.steps.reports.speedByClass.SpeedLineChartSnap.compare(SpeedLineChartSnap.java:31)
	at com.insight.automation.steps.reports.speedByClass.SpeedByClassLineChartSteps.iCanSeeTheLineChartInTheSpeedByClassReportIsMatchingTheSnapshot(SpeedByClassLineChartSteps.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by vinsguru** [comment] 2018-12-17 18:31
As you confirm that it works fine in your local and also from the exception, it seems to be a path issue in the remote machine.  

`C:/Users/Tester/.jenkins/workspace/FT - Grid/src/test/resources/features/modernUI/reports/speedByClass/LineChartSpeedByClass_4710.feature`

- Try to use relative path in case if you use absolute path
- Include the snapshots part of your projects (which you seem to have done)
- Do not export them as jar - because you can not easily read a file from a jar. If you need to export test as jar, then keep the snapshots outside the /src/test/resources

**Comment by vinsguru** [comment] 2018-12-17 18:33
Closing this as it is an user config issue

**Closed as completed by vinsguru** 2018-12-17 18:33 UTC

**Comment by anoop5i** [comment] 2018-12-18 09:29
HI @vinsguru ,

I tried with the relative path but it is failing with the same exception. Do you run these type of tests on Selenium Grid? Looks like the library works only if the CI and execution happens all on the same container. Do you have any other examples with Selenium Grid/cloud based testing providers?

**Comment by vinsguru** [comment] 2018-12-18 14:38
I have used in grid. Can you share the complete code? @anoopsivarajan

**Comment by anoop5i** [comment] 2018-12-18 15:43
Hi @vinsguru Thanks for the reply. Unfortunately I wouldn't be able to share the code. I am using serenity bdd, let me see if I can create a new project and share it with you. I have forked this repo and tried several things. 

It works perfect locally and on jenkins without grid. The webdriver instance produced by the serenity is a wrapper class called WebdriverFacade so that may part of the problem. 

Many thanks for creating this library.

**Comment by ElimaTri** [comment] 2020-01-17 15:19
Hi @vinsguru I am also noticing the same error while running the ocular test cases in selenium GRID 
Unable to write the difference
com.testautomationguru.ocular.exception.OcularException: Unable to write the difference
	at com.testautomationguru.ocular.comparator.ImageUtil.saveImage(ImageUtil.java:60)
	at com.testautomationguru.ocular.comparator.OcularComparator.compare(OcularComparator.java:29)
	at com.testautomationguru.ocular.sample.SampleBuilderImpl.compare(SampleBuilderImpl.java:69)
	at content.bestPractices.seleniumIntegrationTests.pages.BestPracticesPage.comparePage_NavBar(BestPracticesPage.java:88)
	at content.bestPractices.seleniumIntegrationTests.tests.BestPracticesTest.bestPractices_verifyNavBar_isExpected(BestPracticesTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.imageio.IIOException: Can't create an ImageOutputStream!
	at javax.imageio.ImageIO.write(ImageIO.java:1545)
	at org.arquillian.rusheye.oneoff.ImageUtils.writeImage(ImageUtils.java:55)
	at com.testautomationguru.ocular.comparator.ImageUtil.saveImage(ImageUtil.java:58)
	... 40 more
What do you suggest could be the issue
